import type { Lang } from "./types";

const en = {
  tagline: "Latex & modestwear",
  closet: "Closet",
  looks: "Looks",
  overview: "Overview",
  settings: "Settings",
  about: "About",
  pieces: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
  ofPieces: (shown: number, total: number) => `${shown} of ${total}`,
  searchPieces: "Search name, brand, place",
  searchLooks: "Search looks",
  fieldAll: "All fields",
  fieldName: "Name",
  fieldBrand: "Brand",
  fieldLocation: "Place",
  allCategories: "All",
  allStatuses: "All statuses",
  attentionFilter: "Needs a look",
  status: {
    closet: "In closet",
    wearing: "Wearing",
    loan: "On loan",
    cleaner: "At the cleaner",
    repair: "In repair",
    retired: "Donated / sold",
  },
  category: {
    catsuit: "Catsuit",
    bodysuit: "Bodysuit",
    maid: "Maid",
    mask: "Mask",
    gloves: "Gloves",
    boots: "Boots",
    hijab: "Hijab",
    khimar: "Khimar",
    niqab: "Niqab",
    burqa: "Burqa",
    abaya: "Abaya",
    undercap: "Undercap",
  },
  condition: {
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    worn: "Worn",
  },
  sort: {
    newest: "Newest",
    oldest: "Oldest",
    custom: "Custom",
    az: "Name A–Z",
    za: "Name Z–A",
  },
  care: {
    wash: "Wash",
    shine: "Shine",
    chlorinate: "Chlorinate",
    patch: "Patch",
    "dry-clean": "Dry clean",
    alter: "Alteration",
    repair: "Repair",
    polish: "Polish",
    restitch: "Restitch",
  },
  select: "Select",
  cancel: "Cancel",
  delete: "Delete",
  deleteN: (n: number) => `Delete ${n}`,
  confirmPieces: (n: number) =>
    n === 1 ? "Remove this piece from the closet?" : `Remove ${n} pieces from the closet?`,
  confirmLooks: (n: number) => (n === 1 ? "Delete this look?" : `Delete ${n} looks?`),
  confirmErase: "Erase the whole wardrobe on this device? Export a backup first if you want it back.",
  emptyTitle: "The rail is empty",
  emptyBody: "Add a catsuit, a hijab, a pair of gloves — whatever you actually own.",
  emptyLooksTitle: "No looks yet",
  emptyLooksBody: "Group pieces into outfits you can check before you leave.",
  emptyFilter: "Nothing matches.",
  clearFilters: "Clear filters",
  addPiece: "Add piece",
  addLook: "New look",
  edit: "Edit",
  save: "Save",
  back: "Back",
  close: "Close",
  name: "Name",
  brand: "Brand",
  size: "Size",
  color: "Color",
  colorName: "Color name",
  material: "Material",
  thickness: "Thickness",
  thicknessHint: "Latex only, in millimetres. Transparent is a color, not a thickness.",
  laneAll: "All",
  laneLatex: "Latex",
  laneMuslimah: "Muslimah",
  materialName: {
    Latex: "Latex",
    "Chlorinated latex": "Chlorinated latex",
    "Metallic latex": "Metallic latex",
    "Transparent latex": "Transparent latex",
    Silicone: "Silicone",
    Chiffon: "Chiffon",
    Jersey: "Jersey",
    Nida: "Nida",
    Crepe: "Crepe",
    Cotton: "Cotton",
  },
  swatchName: {
    transparent: "Transparent",
    "sheer-black": "Sheer black",
    "sheer-red": "Sheer red",
    black: "Black",
    red: "Red",
    white: "White",
    pink: "Pink",
    purple: "Purple",
    navy: "Navy",
    emerald: "Emerald",
    silver: "Silver",
    natural: "Natural",
  },
  place: "Where it lives",
  conditionLabel: "Condition",
  statusLabel: "Status",
  categoryLabel: "Category",
  notes: "Notes",
  photos: "Condition photos",
  camera: "Camera",
  library: "Library",
  photoHint: "Photos are resized on this device and saved with the piece.",
  swatch: "Color",
  purchase: "Purchase",
  purchased: "Purchased",
  price: "Price paid",
  value: "Estimated value",
  careLog: "Care log",
  noCare: "No care notes yet.",
  careDate: "Date",
  careAction: "What was done",
  careCost: "Cost",
  careNotes: "Note",
  addCare: "Add entry",
  remove: "Remove",
  required: "Name it first.",
  ready: "Ready",
  check: "Check",
  readyBody: "Every piece is home and wearable.",
  blockedBody: "Something in this look is out, in repair, or gone.",
  missing: (n: number) => (n === 1 ? "1 piece missing" : `${n} pieces missing`),
  inThisLook: "In this look",
  choosePieces: "Pieces",
  occasion: "Note",
  totalPieces: "In the closet",
  estValue: "Estimated value",
  byCategory: "By category",
  attention: "Needs attention",
  attentionNone: "Nothing is out, at the cleaner, or in repair.",
  wearingNow: "On you now",
  wearingNone: "Nothing marked as wearing.",
  retiredCount: (n: number) => (n === 1 ? "1 donated or sold" : `${n} donated or sold`),
  open: "Open",
  backup: "Backup",
  export: "Export JSON",
  import: "Import JSON",
  backupHelp: "Includes photos. Worth doing before you clear this browser or switch phones.",
  imported: "Backup restored.",
  importFailed: "That file isn’t a Hem backup.",
  storageFull: "This browser is full — remove a few photos or export and trim the closet.",
  erase: "Erase wardrobe",
  choices: "Choices",
  choicesHelp: "These are the chips and menus on screen. Add, rename, or remove them. A piece that used a removed choice keeps it until you edit that piece.",
  editChoices: "Edit choices",
  resetChoices: "Reset choices",
  confirmResetChoices: "Put every menu back to the built-in latex and modestwear set?",
  laneGroup: "Groups",
  categoryGroup: "Categories",
  statusGroup: "Statuses",
  conditionGroup: "Conditions",
  materialGroup: "Materials",
  colorGroup: "Colors",
  thicknessGroup: "Thicknesses",
  careGroup: "Care actions",
  flagAttention: "Needs a look",
  flagBlocks: "Blocks a look",
  flagArchive: "Left the closet",
  flagWearing: "Wearing now",
  flagLatex: "Latex sheet",
  finishSolid: "Solid",
  finishClear: "Transparent",
  finishSheer: "Sheer",
  addChoice: "Add",
  choicesDone: "Done",
  aboutBody:
    "Hem is a private ledger for latex and modestwear: catsuits, masks, maid pieces, hijab, burqa, and the rest. Latex records color — including transparent — and sheet thickness. Everything stays in this browser.",
  version: "Version 1.1",
  reorder: "Reorder",
  moveUp: "Move up",
  moveDown: "Move down",
  grip: "Drag to reorder",
  deletePiece: "Delete piece",
  deleteLook: "Delete look",
  noneSelected: "Select pieces",
  lookCount: (n: number) => (n === 1 ? "1 piece" : `${n} pieces`),
  costToDate: "Care to date",
  notFound: "That piece is no longer in the closet.",
  saveLook: "Save look",
  untitled: "Untitled",
};

export type Copy = typeof en;

export const copy = { en };

export function careLabel(action: string, _lang: Lang): string {
  if (action in copy.en.care) {
    return copy.en.care[action as keyof Copy["care"]];
  }
  return action;
}
