import type { Look, Piece } from "./types";

export const SAMPLE_PIECES: Piece[] = [
  {
    id: "p-catsuit",
    name: "Black latex catsuit",
    nameZh: "黑色乳胶连体衣",
    category: "catsuit",
    brand: "Libidex",
    size: "M",
    color: "Black",
    colorZh: "黑色",
    material: "Latex",
    materialZh: "乳胶",
    thicknessMm: 0.4,
    condition: "excellent",
    status: "wearing",
    location: "Hanging, bedroom",
    locationZh: "卧室悬挂",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2024-11-02",
    purchasePrice: 680,
    estimatedValue: 520,
    notes: "Back zip. Shined last week.",
    notesZh: "后拉链。上周上过光。",
    care: [{ id: "c-cat", date: "2026-09-12", action: "shine", cost: 0, notes: "" }],
    createdAt: 1730500000000,
    order: 1,
  },
  {
    id: "p-mask",
    name: "Black latex hood",
    nameZh: "黑色乳胶头套",
    category: "mask",
    brand: "Honour",
    size: "One size",
    color: "Black",
    colorZh: "黑色",
    material: "Latex",
    materialZh: "乳胶",
    thicknessMm: 0.6,
    condition: "good",
    status: "closet",
    location: "Drawer 1",
    locationZh: "第一抽屉",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2025-02-18",
    purchasePrice: 140,
    estimatedValue: 110,
    notes: "Eye and mouth openings.",
    notesZh: "眼洞和嘴洞。",
    care: [],
    createdAt: 1739800000000,
    order: 2,
  },
  {
    id: "p-gloves",
    name: "Transparent latex gloves",
    nameZh: "透明乳胶手套",
    category: "gloves",
    brand: "Honour",
    size: "M",
    color: "Transparent",
    colorZh: "透明",
    material: "Transparent latex",
    materialZh: "透明乳胶",
    thicknessMm: 0.25,
    condition: "good",
    status: "cleaner",
    location: "At the polisher",
    locationZh: "在护理店",
    swatch: "#d5e6ee",
    swatchId: "transparent",
    finish: "clear",
    tone: "ink",
    photos: [],
    purchaseDate: "2025-06-01",
    purchasePrice: 48,
    estimatedValue: 30,
    notes: "Opera length. Due back Friday.",
    notesZh: "歌剧长度。周五取回。",
    care: [{ id: "c-gloves", date: "2026-09-22", action: "shine", cost: 12, notes: "" }],
    createdAt: 1748700000000,
    order: 3,
  },
  {
    id: "p-maid",
    name: "Red latex maid dress",
    nameZh: "红色乳胶女仆裙",
    category: "maid",
    brand: "Westward Bound",
    size: "S",
    color: "Red",
    colorZh: "红色",
    material: "Latex",
    materialZh: "乳胶",
    thicknessMm: 0.4,
    condition: "excellent",
    status: "closet",
    location: "Hanging, bedroom",
    locationZh: "卧室悬挂",
    swatch: "#8c2a2a",
    swatchId: "red",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2023-08-14",
    purchasePrice: 420,
    estimatedValue: 300,
    notes: "Apron stored in the same bag.",
    notesZh: "围裙放在同一个袋子里。",
    care: [{ id: "c-maid", date: "2026-05-02", action: "shine", cost: 0, notes: "" }],
    createdAt: 1692000000000,
    order: 4,
  },
  {
    id: "p-boots",
    name: "Black latex thigh boots",
    nameZh: "黑色乳胶过膝靴",
    category: "boots",
    brand: "Syren",
    size: "39",
    color: "Black",
    colorZh: "黑色",
    material: "Latex",
    materialZh: "乳胶",
    thicknessMm: 0.8,
    condition: "fair",
    status: "repair",
    location: "With the maker",
    locationZh: "在店家",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2022-10-09",
    purchasePrice: 540,
    estimatedValue: 260,
    notes: "Left heel seam split.",
    notesZh: "左脚后跟缝线开了。",
    care: [{ id: "c-boots", date: "2026-09-18", action: "patch", cost: 45, notes: "Heel seam." }],
    createdAt: 1665200000000,
    order: 5,
  },
  {
    id: "p-sheer",
    name: "Sheer black bodysuit",
    nameZh: "透黑乳胶连体衣",
    category: "bodysuit",
    brand: "Demask",
    size: "M",
    color: "Sheer black",
    colorZh: "透黑",
    material: "Latex",
    materialZh: "乳胶",
    thicknessMm: 0.4,
    condition: "good",
    status: "closet",
    location: "Drawer 2",
    locationZh: "第二抽屉",
    swatch: "#1a1918",
    swatchId: "sheer-black",
    finish: "sheer",
    tone: "sheet",
    photos: [],
    purchaseDate: "2025-01-20",
    purchasePrice: 310,
    estimatedValue: 240,
    notes: "Unlined. Looks dark until backlit.",
    notesZh: "无衬。逆光才透。",
    care: [],
    createdAt: 1737300000000,
    order: 6,
  },
  {
    id: "p-hijab",
    name: "Black chiffon hijab",
    nameZh: "黑色雪纺头巾",
    category: "hijab",
    brand: "Modanisa",
    size: "Standard",
    color: "Black",
    colorZh: "黑色",
    material: "Chiffon",
    materialZh: "雪纺",
    thicknessMm: null,
    condition: "excellent",
    status: "closet",
    location: "Hijab drawer",
    locationZh: "头巾抽屉",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2025-04-11",
    purchasePrice: 22,
    estimatedValue: 15,
    notes: "Instant, with magnets.",
    notesZh: "方便款，带磁扣。",
    care: [{ id: "c-hijab", date: "2026-09-01", action: "wash", cost: 0, notes: "Cold." }],
    createdAt: 1744300000000,
    order: 7,
  },
  {
    id: "p-burqa",
    name: "Black nida burqa",
    nameZh: "黑色尼达布罩袍",
    category: "burqa",
    brand: "Local tailor",
    size: "54",
    color: "Black",
    colorZh: "黑色",
    material: "Nida",
    materialZh: "尼达",
    thicknessMm: null,
    condition: "good",
    status: "closet",
    location: "Hall closet",
    locationZh: "门厅柜",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2023-03-02",
    purchasePrice: 90,
    estimatedValue: 60,
    notes: "Screen is a separate piece in the same bag.",
    notesZh: "面纱和罩袍放在同一个袋子。",
    care: [],
    createdAt: 1677700000000,
    order: 8,
  },
  {
    id: "p-abaya",
    name: "Navy crepe abaya",
    nameZh: "藏青绉纱阿巴亚",
    category: "abaya",
    brand: "Annahar",
    size: "52",
    color: "Navy",
    colorZh: "藏青",
    material: "Crepe",
    materialZh: "绉纱",
    thicknessMm: null,
    condition: "excellent",
    status: "closet",
    location: "Hall closet",
    locationZh: "门厅柜",
    swatch: "#243044",
    swatchId: "navy",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2024-09-08",
    purchasePrice: 160,
    estimatedValue: 120,
    notes: "Open front, belt inside.",
    notesZh: "开襟，腰带在里面。",
    care: [{ id: "c-abaya", date: "2026-08-20", action: "dry-clean", cost: 18, notes: "" }],
    createdAt: 1725750000000,
    order: 9,
  },
  {
    id: "p-khimar",
    name: "White jersey khimar",
    nameZh: "白色针织希马尔",
    category: "khimar",
    brand: "Inayah",
    size: "One size",
    color: "White",
    colorZh: "白色",
    material: "Jersey",
    materialZh: "针织",
    thicknessMm: null,
    condition: "good",
    status: "loan",
    location: "With Sara",
    locationZh: "在 Sara 那里",
    swatch: "#f4f1ea",
    swatchId: "white",
    finish: "solid",
    tone: "ink",
    photos: [],
    purchaseDate: "2024-06-15",
    purchasePrice: 55,
    estimatedValue: 35,
    notes: "Borrowed for a wedding. Ask back in October.",
    notesZh: "婚礼借出，十月要回来。",
    care: [],
    createdAt: 1718400000000,
    order: 10,
  },
  {
    id: "p-cap",
    name: "Black undercap",
    nameZh: "黑色内帽",
    category: "undercap",
    brand: "Modanisa",
    size: "M",
    color: "Black",
    colorZh: "黑色",
    material: "Cotton",
    materialZh: "棉",
    thicknessMm: null,
    condition: "good",
    status: "closet",
    location: "Hijab drawer",
    locationZh: "头巾抽屉",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2025-04-11",
    purchasePrice: 8,
    estimatedValue: 5,
    notes: "Ties at the nape.",
    notesZh: "颈后系带。",
    care: [],
    createdAt: 1744300001000,
    order: 11,
  },
  {
    id: "p-niqab",
    name: "Black niqab",
    nameZh: "黑色面纱",
    category: "niqab",
    brand: "Local tailor",
    size: "One size",
    color: "Black",
    colorZh: "黑色",
    material: "Nida",
    materialZh: "尼达",
    thicknessMm: null,
    condition: "good",
    status: "closet",
    location: "Hijab drawer",
    locationZh: "头巾抽屉",
    swatch: "#1a1918",
    swatchId: "black",
    finish: "solid",
    tone: "sheet",
    photos: [],
    purchaseDate: "2023-03-02",
    purchasePrice: 25,
    estimatedValue: 15,
    notes: "Single layer.",
    notesZh: "单层。",
    care: [],
    createdAt: 1677700001000,
    order: 12,
  },
];

export const SAMPLE_LOOKS: Look[] = [
  {
    id: "l-black",
    name: "Black latex set",
    nameZh: "全黑乳胶",
    notes: "Catsuit, hood, and gloves.",
    notesZh: "连体衣、头套和手套。",
    pieceIds: ["p-catsuit", "p-mask", "p-gloves"],
    createdAt: 1754000000000,
    order: 1,
  },
  {
    id: "l-maid",
    name: "Maid",
    nameZh: "女仆",
    notes: "Dress with the clear gloves.",
    notesZh: "女仆裙配透明手套。",
    pieceIds: ["p-maid", "p-gloves"],
    createdAt: 1755000000000,
    order: 2,
  },
  {
    id: "l-covered",
    name: "Full cover",
    nameZh: "全身罩袍",
    notes: "Burqa, niqab, and undercap.",
    notesZh: "罩袍、面纱和内帽。",
    pieceIds: ["p-burqa", "p-niqab", "p-cap"],
    createdAt: 1756000000000,
    order: 3,
  },
  {
    id: "l-day",
    name: "Day hijab",
    nameZh: "日间头巾",
    notes: "Abaya, hijab, khimar.",
    notesZh: "阿巴亚、头巾、希马尔。",
    pieceIds: ["p-abaya", "p-hijab", "p-khimar"],
    createdAt: 1757000000000,
    order: 4,
  },
];
